// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ExamManager.Models
{
    public partial class Answer
    {
        public Answer()
        {
            QuestionAnswerMaps = new HashSet<QuestionAnswerMap>();
        }

        public string Id { get; set; }
        public string Answer1 { get; set; }

        public virtual ICollection<QuestionAnswerMap> QuestionAnswerMaps { get; set; }
    }
}