// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ExamManager.Models
{
    public partial class QuestionAnswerMap
    {
        public string QuestionId { get; set; }
        public string AnswerId { get; set; }

        public virtual Answer Answer { get; set; }
        public virtual Question Question { get; set; }
    }
}