// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ExamManager.Models
{
    public partial class Question
    {
        public int QuestionId { get; set; }
        public string Question1 { get; set; }
        public int QuestionLevel { get; set; }
        public string Answer { get; set; }
    }
}