// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ExamManager.Models
{
    public partial class Question
    {
        public Question()
        {
            QuestionAnswerMaps = new HashSet<QuestionAnswerMap>();
        }

        public string Id { get; set; }
        public string Question1 { get; set; }
        public string QuestionLevel { get; set; }

        public virtual ICollection<QuestionAnswerMap> QuestionAnswerMaps { get; set; }
    }
}